config/routes.rb
# Is file mein application k sare routes define kiye gaye hain
Rails.application.routes.draw do
  # User authentication k routes (login, signup, etc.)
  devise_for :users, controllers: { registrations: 'registrations' }
  
  # Discussions k routes, aur har discussion k andar replies k routes
  resources :discussions do
    resources :replies
  end

  # Admin panel k routes, admin dashboard aur users management k liye
  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
    resources :users
  end

  # Root route - application ka homepage
  root 'discussions#index'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  enum role: { user: 0, admin: 1 }
  
  has_many :discussions, dependent: :destroy
  has_many :replies, dependent: :destroy
  
  def admin?
    role == "admin"
  end
  
  def can_modify_discussion?(discussion)
    admin? || discussion.user_id == id
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :check_admin
    before_action :set_user, only: [:edit, :update, :destroy]
    layout 'admin'

    def index
      @users = User.all.order(created_at: :desc)
    end

    def new
      @user = User.new
    end

    def edit
    end

    def create
      @user = User.new(user_params)

      if @user.save
        redirect_to admin_users_path, notice: 'User was successfully created.'
      else
        render :new
      end
    end

    def update
      if user_params[:password].blank?
        user_params.delete(:password)
        user_params.delete(:password_confirmation)
      end

      if @user.update(user_params)
        redirect_to admin_users_path, notice: 'User was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @user.destroy
      redirect_to admin_users_path, notice: 'User was successfully deleted.'
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :admin)
    end

    def check_admin
      unless current_user&.admin?
        redirect_to root_path, alert: 'You are not authorized to access this area.'
      end
    end
  end
end 

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  def new
    @user_types = ['user', 'admin']
    super
  end

  def create
    build_resource(sign_up_params)
    resource.role = params[:user][:role]

    if resource.save
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        if resource.admin?
          redirect_to admin_dashboard_path
        else
          redirect_to root_path
        end
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        redirect_to root_path
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
  end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def dashboard
    @my_discussions = current_user.discussions
    @my_replies = current_user.replies
  end
end 

app/views/admin/users/index.html.erb
<div class="level">
  <div class="level-left">
    <div class="level-item">
      <h1 class="title">Manage Users</h1>
    </div>
  </div>
  <div class="level-right">
    <div class="level-item">
      <%= link_to new_admin_user_path, class: "button is-primary" do %>
        <span class="icon">
          <i class="fas fa-user-plus"></i>
        </span>
        <span>Add New User</span>
      <% end %>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-content">
    <div class="table-container">
      <table class="table is-fullwidth is-striped is-hoverable">
        <thead>
          <tr>
            <th>Email</th>
            <th>Role</th>
            <th>Discussions</th>
            <th>Replies</th>
            <th>Joined</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= gravatar_image_tag(user.email, size: 24, class: 'is-rounded mr-2') %>
                <%= user.email %>
              </td>
              <td>
                <span class="tag <%= user.admin? ? 'is-info' : 'is-light' %>">
                  <%= user.admin? ? 'Admin' : 'User' %>
                </span>
              </td>
              <td><%= user.discussions.count %></td>
              <td><%= user.replies.count %></td>
              <td><%= time_ago_in_words(user.created_at) %> ago</td>
              <td>
                <div class="buttons are-small">
                  <%= link_to edit_admin_user_path(user), class: "button is-info is-light" do %>
                    <span class="icon"><i class="fas fa-edit"></i></span>
                  <% end %>
                  
                  <% unless user == current_user %>
                    <%= link_to admin_user_path(user), 
                        method: :delete, 
                        data: { confirm: "Are you sure you want to delete this user?" }, 
                        class: "button is-danger is-light" do %>
                      <span class="icon"><i class="fas fa-trash"></i></span>
                    <% end %>
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div> 